language: python
env:
  global:
  - USER="Travis on behalf of songGithub"
  - EMAIL="songjin@hotmail.com"
  - REPO="songgithub.github.io"
  - FILES="output/*"
  - GH_REPO="github.com/SongGithub/songgithub.github.io.git"
  - secure: CpEYdCX126DubLz9Tv4gLNGMYoQt9Ze1fCmWvBYzqf+sF8gcL4Snf392rfH5VfV1EFjY445PbaAzSVAYV/DnXUjDiNoQJ5MwtcvMu+5B0CQIn11bK0vgnNeLVE+KQqMLBQG/8mPsEHYOyBZk/ZcO6iujaQ60CPPi6seRZXxuNZ6ufGmsknLhwW9+KHX71Q4aCUktywUpeS6Oiwt9QhunS3UWDqVOQFHvgHDiffhbg0Zx3tZ3gztwc7A61pi7Tu0WvjTOVGHVv87txypw85LQSXE/jlTwGP/bKKdRkWFXuzqGs7s/mM23WRLcGuJne33oSVq86Glq8s572ZCoNd3FoivMo/QFCw9PHb83Ln56KeipM9fdmukREdO9STWFdk3YBhEEfAfM8haTZYMIfDsUTNPDoJqFYZ6OURCbX+YuWT4OdVcs1+0Jt94rGEja5dY0N/HMRuGlMYdoUx8w32xiPyX3cwsYLApxjbgcHlKmGRGDpG3PE1CeM/jUJ8L6JusnfbqjUQI1SWTJET2mbBCt85QmRtNRfDUBhqWitPNc/NTiDT5Fms2f8vyXsJjFlhfKEIGfHWV9TLyuBKuW0js9b1WucSjsHY/dwfzX1RgqBkqIxPZdLrTF0FzWtek0sq3MAsmjK0xrKOCCVbQXOQUy6ERXWoKy5eOgRIBxy2YkJaU=
script:
- pip install pelican markdown
- make publish
after_success:
- pwd
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone git://${GH_REPO}
- ls
- rm -rf ./${REPO}/*
- ls
- mv ${FILES} ${REPO}
- ls ${REPO}/
- cd ${REPO}
- git checkout master
- git push "https://${GH_TOKEN}@${GH_REPO}" master
- git config user.email ${EMAIL}
- git config --local user.name "${USER}"
- git add .
- git status
- git commit -m "${MESSAGE}"
- git status
- git push "https://${GH_TOKEN}@${GH_REPO}" master
