script:
  - make
after_success:
  - .travis/compile.sh


env:
  global:
    secure: RiW7Y7/UU/cjmpebWAkJnT6/sIRAlQVcpos2c98ysKi73IoKmzll4SB2u+wDPo6rYPcYVuFmVHuqHa9tt6iBkE2VNO1OSXK1B18d54/0PwREPbR2hzUTV4D8L14+vKBDe4mO06RX3C1ou6bKhZ/xsYfvwb6ZZ7ThoHHdO65SlopHyTa1Jj9lytKh3MFDsiv2NqqMumj679LWBYACviK6hQ7rSBs7hrXHNTij84XCxEZrkmEsJ2Q6QRKVjy/eaRWmaO79ID2gRUiomfF+oFXULmFdYXyDewceZtG5NgsrqNbbaMq8Gt/Jv2U+F53QNMu1DOP6k34aJGQFhIW5gEdJ6Knd7qWsC0AKx+OHSdLZGYOg854TS0TcwrAc0wOAs8e/Pf/HToOurc5yOxKuV3DbxK9maWc1PGJTQ/PraCLlTpccFb9HAEAy+JUAkYXw3FwOUNq3x5QVSHcsweXW2cnF2y3y1ZZWLs22O4ktw8mNzEVvWU+bKwSCFBPLjbhHB0/Clt44FyBegXfY/Strlyw14Jc5YXD0/fDmsajXqt3mKL9cQA22V9u2ZcGf00F5BV9rubVVNeE9mky5sBGYOPJGdrkpcHZ4eDYlBPm521NZ5cy9MRXwhPuLnjNA2Q4q//MpKJZdrK0YWpXOe2W+4aZ5rji2dj+af8MCCnP4tmHMyps=

