---
version: '3.0'

services:
  pelican:
    image: songgithub/python36-pelican:latest
    working_dir: /app
    volumes:
      - ".:/app"
    entrypoint: pelican
    # entrypoint: ["/bin/bash"]
  bash-git:
    image: ellerbrock/alpine-bash-git:latest
    # working_dir: /app
    # volumes:
    #   - ".:/app"
    entrypoint: /bin/bash
