---
version: '2.1'

services:
  pelican-py:
    image: songgithub/python36-pelican:latest
    working_dir: /app
    volumes:
      - ".:/app"

  pelican-server:
    image: songgithub/python36-pelican:latest
    working_dir: /app
    volumes:
      - "./output/.:/app"
